name = "ebuney"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Shared build-time environment variables for Pages builds
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://grxyvzpapamomhfipjfk.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeHl2enBhcGFtb21oZmlwamZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5OTU0NzUsImV4cCI6MjA4MTU3MTQ3NX0.ra5d_dWmFaGojKWsl0RqCSz7MzEyZu5P8lVp1GQ5ywE"

[env.production]
name = "ebuney"

[env.preview]
name = "ebuney-preview"

